// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHdtCA23ZnJM6Gb525fCMycF3XJE4zIAc',
    appId: '1:434863572823:web:c24c60f9c7da995ab06012',
    messagingSenderId: '434863572823',
    projectId: 'expense-36af2',
    authDomain: 'expense-36af2.firebaseapp.com',
    storageBucket: 'expense-36af2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlUOsINNRcWYkKEsIUGwHBjG7UCgy1OSw',
    appId: '1:434863572823:android:7f2d1347b33185ffb06012',
    messagingSenderId: '434863572823',
    projectId: 'expense-36af2',
    storageBucket: 'expense-36af2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCfLVrHspHHgKqIgozBGlTDcn0Bhed_Hw',
    appId: '1:434863572823:ios:ba8a10e5cbda7a19b06012',
    messagingSenderId: '434863572823',
    projectId: 'expense-36af2',
    storageBucket: 'expense-36af2.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCfLVrHspHHgKqIgozBGlTDcn0Bhed_Hw',
    appId: '1:434863572823:ios:ba8a10e5cbda7a19b06012',
    messagingSenderId: '434863572823',
    projectId: 'expense-36af2',
    storageBucket: 'expense-36af2.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHdtCA23ZnJM6Gb525fCMycF3XJE4zIAc',
    appId: '1:434863572823:web:262ddff9740a32a2b06012',
    messagingSenderId: '434863572823',
    projectId: 'expense-36af2',
    authDomain: 'expense-36af2.firebaseapp.com',
    storageBucket: 'expense-36af2.firebasestorage.app',
  );
}
